ForwardDiff with Interval partials
This change supports differentiation of functions with interval-valued
partials, like

    x, w = 2.0, interval(-0.5, 0.5)
    ForwardDiff.derivative(t -> (x + t*w)^4, 0.0)

Previously, those failed due to a short-circuit in ForwardDiff,
triggering

    ERROR: InconclusiveBooleanOperation: The operation
    `[0.0, 0.0]_com == [-0.5, 0.5]_com_NG` cannot be determined
    unambiguously.

This short-circuits the short-circuit, by specializing `Base.iszero` on
Interval-containing `ForwardDiff.Dual` and `ForwardDiff.Partials`. No
behavior change in IntervalArithmetic itself is needed.